[package]
name = "qingmu-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_runtime.workspace = true
deno_core.workspace = true
deno_ast.workspace = true
reqwest.workspace = true
tokio.workspace = true
serde.workspace = true
anyhow.workspace = true